### ISSUE TITLE
Possible issue.

### ISSUE THREAD

**Issue by peturgq** [goosedefi/goose-contracts-incubator#3]
I was taking a look at the contracts and I don't know much about solidity but can you explain how this is safe?
 Wouldn't anyone be able to call this on the GG1 contract, same for approve?
 ```
function transferFrom (address sender, address recipient, uint256 amount) public override returns (bool) {
        _transfer(sender, recipient, amount);
        _approve(
            sender,
            _msgSender(),
            _allowances[sender][_msgSender()].sub(amount, 'BEP20: transfer amount exceeds allowance')
        );
        return true;
    }

**Comment by gooseadmin** [comment]
> I was taking a look at the contracts and I don't know much about solidity but can you explain how this is safe?
> Wouldn't anyone be able to call this on the GG1 contract, same for approve?
> 
> ```
> function transferFrom (address sender, address recipient, uint256 amount) public override returns (bool) {
>        _transfer(sender, recipient, amount);
>        _approve(
>            sender,
>            _msgSender(),
>            _allowances[sender][_msgSender()].sub(amount, 'BEP20: transfer amount exceeds allowance')
>        );
>        return true;
>    }
> ```

There is no need to be of concern. This is actually the standard code for all ERC20 or BEP20 tokens.

As you can verify youself here from OpenZeppelin: 
https://github.com/OpenZeppelin/openzeppelin-contracts/blob/release-v2.5.0/contracts/token/ERC20/ERC20.sol

or here from Binance:
https://docs.binance.org/smart-chain/developer/BEP20Token.template

To address your concern. the transferFrom requires the user approve a target account with a certain amount of allowance in order for this transfer to go through. Therefore it is vital that a user should never approve any contracts that is not trusted and may contain malicious code to steal you tokens. This applies to all ERC20/BEP20 tokens.
Funds have been stolen by malicious contracts before using this, by scamming the users into approving their malicious contract an infinite allowance.
You can see an example of such case on our medium blog regarding the HoneySwap rugpull.
